---
title: "02. Overview plots"
params: 
  se_dir: "data/se.rds"
  out_plots_dir: "plots"
  out_data_dir: "data"
  filtered_data_dir: "filtered"
  ephys_path: "ephys.csv"
output:
  html_document:
    theme: cerulean
    toc: yes
    toc_float: yes
    smooth_scroll: yes
  pdf_document:
    toc: yes
---

```{r setup}
suppressPackageStartupMessages({
  library(SummarizedExperiment)
  library(edgeR)
  library(ggplot2)
  library(ggrepel)
  library(patchwork)
  library(data.table)
  library(viridis)
  library(PCAtools)
  library(DESeq2)
  library(haven)
})

# Color-blind friendly palettes
cbbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", 
                "#0072B2", "#D55E00", "#CC79A7")
filtDir <- params$filtered_data_dir
ephysPath <- params$ephys_path
outPlotDir <- params$out_plots_dir
outDir <- params$out_data_dir

exSeq <- c("E25", "E27", "E29", "E43")
exSpike <- c("E3", "E11", "E24", "E25", "E28", 
             "E31", "E32", "E33", "E42", "E48", 
             "E63", "E65") # E39 ? 
exDepol <- c("E10", "E15", "E18","E49", "E52") 
```

## Overview Plots

### Import SE

```{r, import se}
if(!dir.exists("plots")) dir.create("plots")
seDir <- params$se_dir
se <- readRDS(seDir)
```

### Comparison Batch2 & Batch3

```{r, error=TRUE}
se <- readRDS(seDir)
seRepSub <- se[, (se$actual_cell_name %in% paste0("E", 24:31))]
seRepSub <- seRepSub[grepl("miRNA", rownames(seRepSub)) | grepl("miR", rownames(seRepSub))]
cd <- as.data.frame(colData(seRepSub))
mapDt <- data.table(cell=colnames(seRepSub),
                    cell_name=seRepSub$actual_cell_name,
                    batch=seRepSub$batch,
                    to_be_removed=seRepSub$to_be_removed,
                    n_clean_reads=cd$Clean_Reads,
                    n_miRNA=colSums(assays(seRepSub)$counts),
                    n_unique_miRNA=colSums(assays(seRepSub)$counts>0), 
                    n_match_genome=cd$Match_Genome,
                    isActivated=cd$isActivated)
mapDt[,mapping_rate:=n_match_genome/n_clean_reads]
mapDt[,miRNA_mapping_rate:=n_miRNA/n_clean_reads]
mapDt[,batch:=factor(batch)]

p1 <- ggplot(mapDt, aes(x=cell_name, fill=batch, color=batch, y=n_miRNA))+
      geom_col(position = position_dodge(1))+
      labs(x="Samples", y="Number of reads mapping to miRNAs")+
      scale_fill_manual(values=cbbPalette)+
      scale_color_manual(values=cbbPalette)+
      theme_bw()
p2 <- ggplot(mapDt, aes(x=cell_name, fill=batch, color=batch, y=miRNA_mapping_rate))+
      geom_col(position = position_dodge(1))+
      labs(x="Samples", y="Rate of matching reads mapping to miRNAs")+
      scale_fill_manual(values=cbbPalette)+
      scale_color_manual(values=cbbPalette)+
      theme_bw()
p3 <- ggplot(mapDt, aes(x=cell_name, fill=batch, color=batch, y=n_unique_miRNA))+
      geom_col(position = position_dodge(1))+
      labs(x="Samples", y="Number of unique miRNAs detected")+
      scale_fill_manual(values=cbbPalette)+
      scale_color_manual(values=cbbPalette)+
      theme_bw()

p1 + p2 + p3 + plot_layout(guides = "collect")
ggsave(file.path(outPlotDir, "01.1_comparison_miRNA_bar.png"), width=35, height=10, units="cm")

p1 <- ggplot(mapDt, aes(x=cell_name, fill=batch, color=batch, y=n_clean_reads))+
      geom_col(position = position_dodge(1))+
      labs(x="Samples", y="Number of clean reads")+
      scale_fill_manual(values=cbbPalette)+
      scale_color_manual(values=cbbPalette)+
      theme_bw()
p2 <- ggplot(mapDt, aes(x=cell_name, fill=batch, color=batch, y=mapping_rate))+
      geom_col(position = position_dodge(1))+
      labs(x="Samples", y="Rate of reads mapping to the genome")+
      scale_fill_manual(values=cbbPalette)+
      scale_color_manual(values=cbbPalette)+
      theme_bw()
p1 + p2 + plot_layout(guides = "collect")
ggsave(file.path(outPlotDir, "01.1_comparison_overall_bar.png"), width=25, height=10, units="cm")

mapCompDt <- dcast(mapDt, cell_name~batch, value.var="n_miRNA")
p1 <- ggplot(mapCompDt, aes(x=`2`, y=`3`))+
      geom_point()+
      geom_text_repel(aes(label=cell_name))+
      geom_abline(slope=1, intercept=0, linetype="dashed")+
      xlim(c(0,3000))+
      ylim(c(0,3000))+
      labs(x="Batch 2", y="Batch 3", title="Number of reads mapping to miRNAs")+
      theme_bw()
mapCompDt <- dcast(mapDt, cell_name~batch, value.var="miRNA_mapping_rate")
p2 <- ggplot(mapCompDt, aes(x=`2`, y=`3`))+
      geom_point()+
      geom_text_repel(aes(label=cell_name))+
      geom_abline(slope=1, intercept=0, linetype="dashed")+
      xlim(c(0.005,0.011))+
      ylim(c(0.005,0.011))+
      labs(x="Batch 2", y="Batch 3", title="Rate of matching reads mapping to miRNAs")+
      theme_bw()
mapCompDt <- dcast(mapDt, cell_name~batch, value.var="n_unique_miRNA")
p3 <- ggplot(mapCompDt, aes(x=`2`, y=`3`))+
      geom_point()+
      geom_text_repel(aes(label=cell_name))+
      geom_abline(slope=1, intercept=0, linetype="dashed")+
      xlim(c(100,420))+
      ylim(c(100,420))+
      labs(x="Batch 2", y="Batch 3", title="Number of unique miRNAs detected")+
      theme_bw()
p1 + p2 + p3 + plot_layout(guides = "collect")
ggsave(file.path(outPlotDir, "01.1_comparison_miRNA_scatter.png"), width=35, height=10, units="cm")
```

### Quality Control

#### Read Filtering Stats

```{r, to be done}
filtStats <- list.files(filtDir, 
                        pattern="filtering_stats_*", 
                        recursive=TRUE)
filtStats <- lapply(filtStats, fread)
```

#### Mapping rates

Per-sample:
```{r, fig.width=8, fig.height=12, error=TRUE}
seSub <- se[grepl("miRNA", rownames(se)) | grepl("miR", rownames(se))]
cd <- as.data.frame(colData(se))
mapDt <- data.table(cell=colnames(se),
                    cell_name=se$actual_cell_name,
                    batch=se$batch,
                    to_be_removed=se$to_be_removed,
                    n_clean_reads=cd$Clean_Reads,
                    n_miRNA=colSums(assays(seSub)$counts),
                    n_match_genome=cd$Match_Genome,
                    isActivated=cd$isActivated)
mapDt[,mapping_rate:=n_match_genome/n_clean_reads]

setorder(mapDt, -mapping_rate)
ggplot(mapDt, aes(x=cell_name, y=mapping_rate, fill=isActivated)) + geom_col() + 
  labs(x="Samples", y="Mapping rate")+
  facet_grid(cols=vars(batch), scales="free_x")+
  scale_fill_manual(values=cbbPalette)+
  scale_x_discrete(guide=guide_axis(n.dodge=2))+
  geom_hline(yintercept=0.4, linetype="dashed")+
  theme_bw()
ggsave(file.path(outPlotDir, "01.1_mapping_rate.png"), 
       width=30, height=12, units="cm")

setorder(mapDt, -n_match_genome)
mapDt$cell_name <- factor(mapDt$cell_name, 
                          levels=c(setdiff(unique(mapDt$cell_name), 
                                           "N. Control"),
                                   "N. Control"), ordered=TRUE)
p1 <- ggplot(mapDt, aes(x=cell_name, y=n_match_genome, fill=isActivated)) + geom_col() + 
  labs(x="Samples", y="Number of reads matching to genome")+
  scale_fill_manual(values=cbbPalette)+
  facet_grid(cols=vars(batch), scales="free_x")+
  scale_x_discrete(guide=guide_axis(n.dodge=2))+
  theme_bw()

# Finally, between 10–50% of total reads matched annotated miRNA loci
mapDt[,miRNA_mapping_rate:=n_miRNA/n_clean_reads]
p2 <- ggplot(mapDt, aes(x=cell_name, y=miRNA_mapping_rate, fill=isActivated)) + geom_col() + 
  labs(x="Samples", y="Rate of matching reads mapping to miRNAs")+
  scale_fill_manual(values=cbbPalette)+
  facet_grid(cols=vars(batch), scales="free_x")+
  scale_x_discrete(guide=guide_axis(n.dodge=2))+
  theme_bw()

p3 <- ggplot(mapDt, aes(x=cell_name, y=n_miRNA, fill=isActivated)) + geom_col() + 
  labs(x="Samples", y="Number of reads mapping to miRNAs")+
  scale_fill_manual(values=cbbPalette)+
  facet_grid(cols=vars(batch), scales="free_x")+
  scale_x_discrete(guide=guide_axis(n.dodge=2))+
  theme_bw()

library(patchwork)
p1 / p2 / p3 + plot_layout(guides = "collect")
ggsave(file.path(outPlotDir, "01.1_miRNA_mapping.png"), width=30, height=26, units="cm")
```

### MA-Plots

```{r,error=TRUE}
se <- se[grepl("miRNA", rownames(se)) | grepl("miR", rownames(se))]

# remove non-covered samples
se <- se[,!(se$to_be_removed) & 
          !(se$actual_cell_name %in% c("E6", "E23")) & 
          !(se$actual_cell_name %in% c(exSeq))]
ephysDt <- fread(ephysPath)
ephysDt[,`sample id`:=paste0("E", gsub("E", "", `sample id`))]
colDt <- merge(as.data.table(colData(se)), 
               ephysDt, 
               by.x=c("actual_cell_name"), 
               by.y=c("sample id"))
colDf <- as(colDt[match(colData(se)$actual_cell_name, 
                              colDt$actual_cell_name), ], 
                  "DataFrame")
rownames(colDf) <- colnames(se)
colData(se) <- colDf

rownames(se) <- unlist(tstrsplit(rownames(se), "/", keep=2))
assays(se)$counts <- floor(assays(se)$counts)

dds <- edgeR::calcNormFactors(DGEList(assay(se), 
                                      group=as.factor(se$isActivated)),
                              method="TMMwsp")
assays(se)$logcpm <- log1p(cpm(dds))
saveRDS(se, file.path(outDir, "02_sports_se.rds"))

# limma::plotMA(assays(se)$logcpm,array = which(se$actual_cell_name=="E9"))
# limma::plotMA(assays(se)$logcpm,array = which(se$actual_cell_name=="E3"))
# 
# limma::plotMA(assays(se)$logcpm,array =  which(se$actual_cell_name=="E18"))
# limma::plotMA(assays(se)$logcpm,array = which(se$actual_cell_name=="E19"))
# limma::plotMA(assays(se)$logcpm,array = which(se$actual_cell_name=="E11"))
```

### Activation groups

#### MDS plots {.tabset}

```{r, error=TRUE}
se <- se[rowSums(assays(se)$counts>0)>10,]

mdsDims <- plotMDS(assays(se)$logcpm, top=20, plot=FALSE)[c("x", "y")]
mdsDt <- as.data.table(mdsDims)
colnames(mdsDt) <- c("MDS1", "MDS2")
mdsDt <- cbind(mdsDt, as.data.table(colData(se)))
mdsDt <- cbind(mdsDt, colSums(assays(se)$counts))
setnames(mdsDt, "V2", "lib_size")
mdsDt$isActivated <- factor(mdsDt$isActivated)

cor(mdsDt$Clean_Reads, mdsDt$lib_size)
```

##### Batch 
```{r, error=TRUE}
ggplot(mdsDt, aes(x=MDS1, y=MDS2, color=as.factor(batch)))+
geom_point(size=2)+
geom_text_repel(aes(label=actual_cell_name))+
scale_color_manual(values=cbbPalette)+
guides(color=guide_legend(title="Batch"))+
theme_bw()
ggsave(file.path(outPlotDir, "02.1_mds_batch.png"),
       device="png", width=20, units="cm")
```

##### Library size
```{r, error=TRUE}
ggplot(mdsDt, aes(x=MDS1, y=MDS2, color=lib_size))+
geom_point(size=2)+
geom_text_repel(aes(label=actual_cell_name))+
scale_color_viridis()+
guides(color=guide_legend(title="Library Size"))+
theme_bw()
ggsave(file.path(outPlotDir, "02.1_mds_library_size.png"),
       device="png", width=20, units="cm")
```

##### Group 
```{r, error=TRUE}
ggplot(mdsDt, aes(x=MDS1, y=MDS2, color=isActivated))+
geom_point(size=2)+
geom_text_repel(aes(label=actual_cell_name))+
scale_color_manual(values=cbbPalette)+
guides(color=guide_legend(title="Activation"))+
theme_bw()
ggsave(file.path(outPlotDir, "02.1_mds_activation.png"),
       device="png", width=20, units="cm")
```

##### Amplitude
```{r, error=TRUE}
seSub <- se[,!(se$actual_cell_name %in% exDepol)]

mdsDims <- plotMDS(assays(seSub)$logcpm, top=20, plot=FALSE)[c("x", "y")]
mdsDt <- as.data.table(mdsDims)
colnames(mdsDt) <- c("MDS1", "MDS2")
mdsDt <- cbind(mdsDt, as.data.table(colData(seSub)))
setnames(mdsDt, c("epsc.ampl...pA."), c("ampl_pa"))
mdsDt[,missing_amp:=fifelse(is.na(ampl_pa), TRUE, FALSE)]

ggplot(mdsDt, aes(x=MDS1, y=MDS2, color=ampl_pa, 
                  alpha=missing_amp))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name), 
                show.legend = FALSE)+
scale_color_viridis(option="C")+
guides(color = guide_colorbar(title="Amplitude (pA)"))+
scale_alpha_manual(values = c("FALSE" = 1, 
                              "TRUE" = 0.5),
                   guide = "none")+
theme_bw()
ggsave(file.path(outPlotDir, "02.1_mds_amplitude.png"),
       device="png", width=20, units="cm")
```

##### Spiking 
```{r, error=TRUE}
seSub <- se[,!(se$actual_cell_name %in% exSpike)]
mdsDims <- plotMDS(assays(seSub)$logcpm, top=20, plot=FALSE)[c("x", "y")]

mdsDt <- as.data.table(mdsDims)
colnames(mdsDt) <- c("MDS1", "MDS2")
mdsDt <- cbind(mdsDt, as.data.table(colData(seSub)))
setnames(mdsDt, c("spiking..Hz."), c("spike_h"))

mdsDt[,spike_h:=as.integer(spike_h)]
mdsDt[,missing_spike:=fifelse(is.na(spike_h), TRUE, FALSE)]
ggplot(mdsDt, aes(x=MDS1, y=MDS2, color=spike_h, alpha=missing_spike))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name), show.legend=FALSE)+
scale_color_viridis(option="C")+
scale_alpha_manual(values = c("FALSE" = 1, 
                              "TRUE" = 0.5),
                   guide = "none")+
guides(color = guide_colorbar(title="Spiking (Hz)"))+
theme_bw()
ggsave(file.path(outPlotDir, "02.1_mds_spiking.png"),
       device="png", width=20, units="cm")
```

##### Frequency
```{r, error=TRUE}
seSub <- se[,!(se$actual_cell_name %in% exDepol)]

mdsDims <- plotMDS(assays(seSub)$logcpm, top=20, plot=FALSE)[c("x", "y")]
mdsDt <- as.data.table(mdsDims)
colnames(mdsDt) <- c("MDS1", "MDS2")
mdsDt <- cbind(mdsDt, as.data.table(colData(seSub)))
setnames(mdsDt, c("epsc.frequ...Hz."), c("freq_hz"))
mdsDt[,missing_freq:=fifelse(is.na(freq_hz), TRUE, FALSE)]

ggplot(mdsDt, aes(x=MDS1, y=MDS2, color=freq_hz, alpha=missing_freq))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name), show.legend=FALSE)+
scale_color_viridis(option="C")+
guides(color = guide_colorbar(title="Frequency (Hz)"))+
scale_alpha_manual(values = c("FALSE" = 1, 
                              "TRUE" = 0.5),
                   guide = "none")+
theme_bw()
ggsave(file.path(outPlotDir, "02.1_mds_frequency.png"),
       device="png", width=20, units="cm")
```

#### PCA {.tabset}

Check further components of PCA plot
```{r, error=TRUE}
# remove low count rows
lcpmSub <- assays(se)$logcpm 
lcpmSub <- lcpmSub[rowSums(lcpmSub>0)>20,]
pcaCpm <- pca(lcpmSub, metadata=colData(se))
pcaCompCpm <- cbind(pcaCpm$rotated[,paste0("PC", 1:10)], colData(se))
pcaCompCpm$isActivated <- as.factor(pcaCompCpm$isActivated)
pcaCompCpm$lib_size <- colSums(assays(se)$counts)
```

##### Group
```{r, error=TRUE}
ggplot(pcaCompCpm, aes(x=PC1, y=PC2, color=isActivated))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name), show.legend=FALSE)+
guides(color=guide_legend(title="Activation"))+
labs(x=paste0("PC1: ", round(pcaCpm$variance[1], 1), "% variance explained"),
     y=paste0("PC2: ", round(pcaCpm$variance[2], 1), "% variance explained"))+
scale_color_manual(values=cbbPalette)+
theme_bw()  
ggsave(file.path(outPlotDir, "02.1_pca_activation.png"),
       device="png", width=20, units="cm")
  
ggplot(pcaCompCpm, aes(x=PC3, y=PC4, color=isActivated))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name), show.legend=FALSE)+
guides(color=guide_legend(title="Activation"))+
labs(x=paste0("PC3: ", round(pcaCpm$variance[3], 1), "% variance explained"),
     y=paste0("PC4: ", round(pcaCpm$variance[4], 1), "% variance explained"))+
scale_color_manual(values=cbbPalette)+
theme_bw()  
```

##### Batch
```{r, error=TRUE}
ggplot(pcaCompCpm, aes(x=PC1, y=PC2, color=as.factor(batch)))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name), show.legend=FALSE)+
labs(x=paste0("PC1: ", round(pcaCpm$variance[1], 1), "% variance explained"),
     y=paste0("PC2: ", round(pcaCpm$variance[2], 1), "% variance explained"))+
guides(color=guide_legend(title="Batch"))+
scale_color_manual(values=cbbPalette)+
theme_bw()  
ggsave(file.path(outPlotDir, "02.1_pca_batch.png"),
       device="png", width=20, units="cm")
  
ggplot(pcaCompCpm, aes(x=PC3, y=PC4, color=as.factor(batch)))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name), show.legend=FALSE)+
labs(x=paste0("PC3: ", round(pcaCpm$variance[3], 1), "% variance explained"),
     y=paste0("PC4: ", round(pcaCpm$variance[4], 1), "% variance explained"))+
guides(color=guide_legend(title="Batch"))+
scale_color_manual(values=cbbPalette)+
theme_bw()  
```

##### Library Size
```{r, error=TRUE}
ggplot(pcaCompCpm, aes(x=PC1, y=PC2, color=lib_size))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name), show.legend=FALSE)+
labs(x=paste0("PC1: ", round(pcaCpm$variance[1], 1), "% variance explained"),
     y=paste0("PC2: ", round(pcaCpm$variance[2], 1), "% variance explained"))+
scale_color_viridis() +
guides(color = guide_colorbar(title="Library Size"))+
theme_bw()  
ggsave(file.path(outPlotDir, "02.1_pca_library_size.png"),
       device="png", width=20, units="cm")
  
ggplot(pcaCompCpm, aes(x=PC3, y=PC4, color=lib_size))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name))+
labs(x=paste0("PC3: ", round(pcaCpm$variance[3], 1), "% variance explained"),
     y=paste0("PC4: ", round(pcaCpm$variance[4], 1), "% variance explained"))+
scale_color_viridis() +
guides(color = guide_colorbar(title="Library Size"))+
theme_bw()  
```

##### Amplitude
```{r, error=TRUE}
seSub <- se[,!(se$actual_cell_name %in% exDepol)]
lcpmSub <- assays(seSub)$logcpm 
lcpmSub <- lcpmSub[rowSums(lcpmSub>0)>20,]
pcaCpm <- pca(lcpmSub, metadata=colData(seSub))
pcaCompCpm <- cbind(pcaCpm$rotated[,paste0("PC", 1:10)], colData(seSub))
pcaCompCpm <- as.data.table(pcaCompCpm)
pcaCompCpm[,amp_missing:=fifelse(is.na(`epsc ampl. (pA)`), TRUE, FALSE)]


ggplot(pcaCompCpm, aes(x=PC1, y=PC2, color=`epsc ampl. (pA)`, 
                       alpha=amp_missing))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name), show.legend=FALSE)+
labs(x=paste0("PC1: ", round(pcaCpm$variance[1], 1), "% variance explained"),
     y=paste0("PC2: ", round(pcaCpm$variance[2], 1), "% variance explained"))+
guides(color = guide_colorbar(title="Amplitude (pA)"))+
scale_alpha_manual(values = c("FALSE" = 1, 
                              "TRUE" = 0.5),
                   guide = "none")+
scale_color_viridis(option="C")+
theme_bw()
ggsave(file.path(outPlotDir, "02.1_pca_amplitude.png"),
       device="png", width=20, units="cm")
  
ggplot(pcaCompCpm, aes(x=PC3, y=PC4, color=`epsc ampl. (pA)`))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name), show.legend=FALSE)+
labs(x=paste0("PC3: ", round(pcaCpm$variance[3], 1), "% variance explained"),
     y=paste0("PC4: ", round(pcaCpm$variance[4], 1), "% variance explained"))+
guides(color = guide_colorbar(title="Amplitude (pA)"))+
scale_color_viridis(option="C")+
theme_bw() 
```

##### Spiking
```{r, error=TRUE}
seSub <- se[,!(se$actual_cell_name %in% exDepol)]
lcpmSub <- assays(seSub)$logcpm 
lcpmSub <- lcpmSub[rowSums(lcpmSub>0)>20,]
pcaCpm <- pca(lcpmSub, metadata=colData(seSub))
pcaCompCpm <- cbind(pcaCpm$rotated[,paste0("PC", 1:10)], colData(seSub))
pcaCompCpm <- as.data.table(pcaCompCpm)
pcaCompCpm[,spike_hz:=as.integer(`spiking (Hz)`)]
pcaCompCpm[,spike_missing:=fifelse(is.na(spike_hz), TRUE, FALSE)]


ggplot(pcaCompCpm, aes(x=PC1, y=PC2, color=spike_hz, alpha=spike_missing))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name), show.legend=FALSE)+
labs(x=paste0("PC1: ", round(pcaCpm$variance[1], 1), "% variance explained"),
     y=paste0("PC2: ", round(pcaCpm$variance[2], 1), "% variance explained"))+
guides(color = guide_colorbar(title="Spiking (Hz)"))+
scale_alpha_manual(values = c("FALSE" = 1, 
                              "TRUE" = 0.5),
                   guide = "none")+
scale_color_viridis(option="C")+
theme_bw()  
ggsave(file.path(outPlotDir, "02.1_pca_spiking.png"),
       device="png", width=20, units="cm")
  
ggplot(pcaCompCpm, aes(x=PC3, y=PC4, color=spike_hz, alpha=spike_missing))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name), show.legend=FALSE)+
labs(x=paste0("PC3: ", round(pcaCpm$variance[3], 1), "% variance explained"),
     y=paste0("PC4: ", round(pcaCpm$variance[4], 1), "% variance explained"))+
guides(color = guide_colorbar(title="Spiking (Hz)"))+
scale_alpha_manual(values = c("FALSE" = 1, 
                              "TRUE" = 0.5),
                   guide = "none")+
scale_color_viridis(option="C")+
theme_bw()  
```

##### Frequency
```{r, error=TRUE}
seSub <- se[,!(se$actual_cell_name %in% exDepol)]
lcpmSub <- assays(seSub)$logcpm 
lcpmSub <- lcpmSub[rowSums(lcpmSub>0)>20,]
pcaCpm <- pca(lcpmSub, metadata=colData(seSub))
pcaCompCpm <- cbind(pcaCpm$rotated[,paste0("PC", 1:10)], colData(seSub))
pcaCompCpm <- as.data.table(pcaCompCpm)
pcaCompCpm[,freq_hz:=as.integer(`epsc frequ. (Hz)`)]
pcaCompCpm[,freq_missing:=fifelse(is.na(freq_hz), TRUE, FALSE)]

ggplot(pcaCompCpm, aes(x=PC1, y=PC2, color=freq_hz, alpha=freq_missing))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name), show.legend=FALSE)+
labs(x=paste0("PC1: ", round(pcaCpm$variance[1], 1), "% variance explained"),
     y=paste0("PC2: ", round(pcaCpm$variance[2], 1), "% variance explained"))+
guides(color = guide_colorbar(title="Frequency (Hz)"))+
scale_alpha_manual(values = c("FALSE" = 1, 
                              "TRUE" = 0.5),
                   guide = "none")+
scale_color_viridis(option="C")+
theme_bw()  
ggsave(file.path(outPlotDir, "02.1_pca_frequency.png"),
       device="png", width=20, units="cm")
  
ggplot(pcaCompCpm, aes(x=PC3, y=PC4, color=freq_hz, alpha=freq_missing))+
geom_point(size=2.5)+
geom_text_repel(aes(label=actual_cell_name), show.legend=FALSE)+
labs(x=paste0("PC3: ", round(pcaCpm$variance[3], 1), "% variance explained"),
     y=paste0("PC4: ", round(pcaCpm$variance[4], 1), "% variance explained"))+
guides(color = guide_colorbar(title="Frequency (Hz)"))+
scale_alpha_manual(values = c("FALSE" = 1, 
                              "TRUE" = 0.5),
                   guide = "none")+
scale_color_viridis(option="C")+
theme_bw()  
```

## Session info

```{r}
sessionInfo()
```
